apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-read-only
  namespace: default
subjects:
  - kind: ServiceAccount
    namespace: default
    name: newsa
roleRef:
  kind: Role
  name: pod-read-only
  apiGroup: rbac.authorization.k8s.io
